# Generated by Django 3.2.6 on 2021-11-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud', models.IntegerField(default=2)),
                ('ataque', models.IntegerField(default=2)),
                ('defensa', models.IntegerField(default=2)),
                ('velataque', models.IntegerField(default=2)),
                ('veldefensa', models.IntegerField(default=2)),
                ('velocidad', models.IntegerField(default=2)),
                ('total', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreevo', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('altura', models.IntegerField(default=2)),
                ('peso', models.IntegerField(default=2)),
                ('habilidades', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evolucion',
                'verbose_name_plural': 'Evoluciones',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('poder', models.IntegerField(default=2)),
                ('accion', models.CharField(max_length=50)),
                ('efecto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('altura', models.IntegerField(default=2)),
                ('peso', models.IntegerField(default=2)),
                ('habilidades', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemones',
            },
        ),
    ]
