# Generated by Django 3.2.6 on 2021-11-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='especie2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
