# Generated by Django 3.2.6 on 2021-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20211102_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
