# Generated by Django 3.2.6 on 2021-11-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
